# Example about LLM tokenizers

In [1]:
from datasets import load_dataset, DatasetDict, Dataset

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer)

from peft import PeftModel, PeftConfig, get_peft_model, LoraConfig
import evaluate
import torch
import numpy as np
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


### Tokenizers

In [2]:
def show_tokens(text:str, model_checkpoint: str):
    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
                                              
    token_ids = tokenizer.encode(text)
    for t in token_ids:
        print(t, end= ' ')
        print(tokenizer.decode(t), end='\n')

In [3]:
for model_name in ["gpt2", "distilbert-base-uncased","facebook/galactica-1.3b"]:
    print(f"Model: {model_name}")
    show_tokens('Hello, this is TEST sentence!#  spaces:    , new_lines: \n\n, equation: 4.0*80=320.0', model_checkpoint=model_name)

Model: gpt2


/opt/miniconda3/envs/llm-finetuning-conda/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


15496 Hello
11 ,
428  this
318  is
43001  TEST
6827  sentence
0 !
2 #
220  
9029  spaces
25 :
220  
220  
220  
837 ,
649  new
62 _
6615 lines
25 :
220  
198 

198 

11 ,
16022  equation
25 :
604  4
13 .
15 0
9 *
1795 80
28 =
19504 320
13 .
15 0
Model: distilbert-base-uncased
101 [CLS]
7592 hello
1010 ,
2023 this
2003 is
3231 test
6251 sentence
999 !
1001 #
7258 spaces
1024 :
1010 ,
2047 new
1035 _
3210 lines
1024 :
1010 ,
8522 equation
1024 :
1018 4
1012 .
1014 0
1008 *
3770 80
1027 =
13710 320
1012 .
1014 0
102 [SEP]
Model: facebook/galactica-1.3b
62 H
13716 ello
34 ,
495  this
343  is
27068  TEST
9553  sentence
23 !
25 #
243  
4682  spaces
48 :
344     
34 ,
1087  new
85 _
9918 lines
48 :
243  
221 

221 

34 ,
1803  equation
48 :
243  
42 4
36 .
38 0
32 *
46 8
38 0
51 =
41 3
40 2
38 0
36 .
38 0
